### ISSUE TITLE
Avtentikacija

### ISSUE THREAD

**Issue by jaanos** [KrusecN13/Smucarski-center#1]
Trenutno v programu s spletno aplikacijo uvozite program `auth.py`, ki ga nimata v repozitoriju, saj vsebuje vaša gesla in je zato v `.gitignore`. To seveda pomeni, da lahko le sami uporabljate aplikacijo. Tako vključite `auth_public.py` namesto `auth.py` v spletni aplikaciji (lahko naredite `import auth_public as auth`, da preostale kode ne bo potrebno spreminjati). V programu za uvoz je seveda v redu, da uvažate `auth.py`.

Seveda bo potrebno uporabniku `javnost` dati ustrezne pravice za uporabo baze (vključno s pravico `INSERT` na tabelah `tekmovalci` in `tekme`, če želite omogočiti sprotne posodobitve), sami pa si lahko daste vse pravice - poglejte si nocmatic/prevozi#4.

**Comment by efodx** [comment]
Sedaj smo dodali v bazo še uporabnike, ki jih takrat ni bilo. Ker se uporabniki sproti posodabljajo, bi morali uporabniku javnost dati praktično vsa dovoljenja za spremembo baze, obstaja kakšna druga možnost?

**Comment by jaanos** [comment]
Da bo mogoča osnovna funkcionalnost uporabnikov, vsekakor potrebuje uporabnik `javnost` vse pravice na tabeli `uporabnik` in števcu `uporabnik_id_uporabnika_seq`, ter pravici `INSERT` in `DELETE` na tabeli `mojiskakalci`. Glede na zasnovo aplikacije (tj., da se podatki samodejno uvozijo v bazo iz spletne strani) bi potem potrebovali še pravico `INSERT` na ostalih tabelah. Drugih pravic ne potrebuje - posebej ne pravic na sami bazi (tj., dodajanje/brisanje tabel).

Ena možnost bi bila, da uporabniku ne omogočite uvažanja podatkov iz spletne strani, pač pa to dovolite samo s svojimi uporabniškimi imeni - morda lahko bazo dopolnite z želenimi podatki do te mere, da bo aplikacija lepo delovala (če je to potrebno).

**Comment by efodx** [comment]
Smo se odločili, da bomo pustili samodejno uvažanje, čeprav je kar počasno. 
Pravice so poštimane zdej. 

Zanima nas, kaj, oziroma če, je treba še kaj dodati/spremeniti na projektu (poleg ER diagrama seveda).

**Comment by jaanos** [comment]
Izgleda več ali manj v redu - svetoval bi le, da nastavite še glavni ključ v tabelah `mojiskakalci` in `rezultati` - v obeh primerih gre za relacije, tako da naj bo glavni ključ sestavljen iz vseh tujih ključev v tabeli (tako npr. preprečite, da bi isti uporabnik imel večkrat istega skakalca).

Ko boste končali, javite, da dodam povezavo na repozitorij predmeta. Medtem se lahko s profesorjem domenite za termin zagovora.

**Comment by efodx** [comment]
Tako, primarni ključi so bili dodani in ER diagram spremenjen. 
Mi bi tukaj zaključili.

**Comment by jaanos** [comment]
V redu, sem dodal povezavo.
