### ISSUE TITLE
Podatkovni tipi

### ISSUE THREAD

**Issue by jaanos** [KrusecN13/Smucarski-center#2]
Vidim, da imajo vsi stolpci v vaših tabelah tip `TEXT`. To spremenite tako, da bo vsak stolpec imel ustrezen tip - torej `INTEGER` za cela števila (vključno z ID-ji), `REAL` za decimalna števila (ali morda celo npr. `NUMERIC(5, 1)` - torej številke z največ 5 mesti, od tega eno decimalno mesto), `DATE` za datume (navedite jih v obliki `yyyy-mm-dd`). Tako bo mogoče te podatke ustrezno primerjati, z njimi računati itd.

Svetoval bi še, da uporabnikom daste še ID-je (uporabite tip `SERIAL`, da se bodo samodejno generirali) in se nanje v tabeli `mojiskakalci` sklicujete po teh ID-jih (tukaj najbo tip seveda `INTEGER`). Prav tako svetujem, da v tabeli `tekmovalci` stolpec `ime` razbijete na stolpca za ime in priimek (slednjega pretvorite v male črke z veliko začetnico - če jih želite prikazati z velikimi črkami, to storite v poizvedbi). Opažam še, da v tabeli `tekme` uvoz najbrž ni narejen pravino, saj imate v stolpcu `kategorija` datume, v stolpcu `datum` pa številko (ustrezna nastavitev podatkovnih tipov bi ujela take napake).

Nazadnje, nastavite še tuje ključe, kadarkoli se z nekim podatkom (navadno z ID-jem) sklicujete na drugo tabelo. SQL stavke za ustvarjanje tabel si shranite v datoteko, da jih boste lahko enostavno še enkrat zagnali, če bo potrebno kaj spremeniti.

**Comment by efodx** [comment]
Tipi so bili popravljeni, prav tako so bili popravljeni uvozi in dodani so bili serijski ključi za uporabnike.
Nastaviti je treba še primarne in tuje ključe.

**Comment by efodx** [comment]
Tuji in primarni ključi so nastavljeni.
